canonical: https://www.medizininformatik-initiative.de/fhir/core/modul-prozedur
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
status: active
version: 2025.0.0
id: mii-ig-prozedur
name: MII_IG_Prozedur
packageId: de.medizininformatikinitiative.kerndatensatz.prozedur
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
dependencies:
  de.basisprofil.r4: 1.5.x
  de.medizininformatikinitiative.kerndatensatz.meta: 2025.0.x

menu:
  Home: index.html
  Artifacts: artifacts.html